### ISSUE TITLE
crash unity on macbook pro m1

### ISSUE THREAD

**Issue by freekatet** [keijiro/UnityMLStableDiffusion#10]
Hi,
I am running Unity 2023.2.3f1 (silicon) , the webcam example.
settings are CPU & GPU on the tester script, original/compiled in the StreamingAssets folder (renamed StableDiffusion)
Unity crashes as soon I get into playmode ( I can see the light of my webcam turning on just before crash)

any idea where I could look at ?

thanks!

**Comment by keijiro** [comment]
Does it work in the "CPU and NE" mode with the split_einsum model?

**Comment by freekatet** [comment]
Sadly not, the same crash happens with this configuration. 
Any logs I could find anywhere?

**Comment by freekatet** [comment]
I saw you are on Sonoma , I am on Ventura (13.4) . Not sure if tehre is any connections.

**Comment by keijiro** [comment]
> I saw you are on Sonoma , I am on Ventura (13.4) . Not sure if tehre is any connections.

It might be relevant because the recent updates in ml-stable-diffusion contains changes requiring Sonoma. I haven't enabled it though.

**Comment by freekatet** [comment]
oh weird, probably not this then as I downloaded the ML SD you linked. Any idea what this could mean ?
AssetImportWorkerClient::OnTransportError - code=2 error=End of file

**Comment by keijiro** [comment]
I think this kind of issue doesn't reproduce with the latest package and macOS 15.0. Please reopen it if it still reproduces.
