### ISSUE TITLE
Prompt doesn't change generate image

### ISSUE THREAD

**Issue by felixopixido** [keijiro/UnityMLStableDiffusion#9]
Hello, I try to test your project https://github.com/keijiro/UnityMLStableDiffusion but I have a problem. The prompt doesn't change the generate image. I test on a M1 and M2 max. Do you know what can I test to solve this issue? Many thanks and I love your jobs, continue :)

![capture](https://github.com/keijiro/UnityMLStableDiffusion/assets/12746646/b586b4d8-e468-476e-a67c-acc33ccb0262)

**Comment by felixopixido** [comment]
Same :(

![renderToImage](https://github.com/keijiro/UnityMLStableDiffusion/assets/12746646/10c48187-fa04-466d-b287-f4e840c82689)
![imageToImage](https://github.com/keijiro/UnityMLStableDiffusion/assets/12746646/6e9ea4bf-97fe-4f79-a763-904ffcb9af1f)

**Comment by keijiro** [comment]
How it looks with the default prompt (IIRC, it's "Surrealistic painting by J. C. Leyendecker")?

**Comment by felixopixido** [comment]
![renderToImage](https://github.com/keijiro/UnityMLStableDiffusion/assets/12746646/30e89823-a6f0-4e32-b584-e4e7562b4f5c)
![imageToImage](https://github.com/keijiro/UnityMLStableDiffusion/assets/12746646/6fc556a7-c39d-4fcb-9e44-62ce9705436c)
![webcamToImage](https://github.com/keijiro/UnityMLStableDiffusion/assets/12746646/7c14bfe7-8d2a-42b5-ad63-53bbbd263d02)

It almost doesn't change anything. It was like the prompt was not taken to generate  the image or I miss something?

**Comment by keijiro** [comment]
It doesn't look like J. C. Leyendecker. Are you actually using coreml-stable-diffusion-2-base?

**Comment by keijiro** [comment]
> I use this: https://huggingface.co/apple/coreml-stable-diffusion-2-base, and the "split_einsum/compiled" folder

Thanks for the clarification. Okay. You're using the right one.

It seems the UI isn't working correctly.

You can manually set a prompt without the UI by modifying the following line:
https://github.com/keijiro/UnityMLStableDiffusion/blob/main/Assets/Test/Tester.cs#L76

Could you try assigning a prompt string to it?

**Comment by felixopixido** [comment]
Yes I have already try this:
//_pipeline.Prompt = _uiPrompt.text;
_pipeline.Prompt = "painting, the starry night, vincent van gogh";
But same no visible change on the generate image. Same result roughly.

Like stable diffusion doesn't take the prompt.

I test with Unity 2023.1.0.

**Comment by keijiro** [comment]
How about other parameters like Strength? You will get completely random image when setting Strength = 1.

**Comment by felixopixido** [comment]
Hi,
Here many screenshot with differents values
![webcamToImage_0-2](https://github.com/keijiro/UnityMLStableDiffusion/assets/12746646/d8828402-c6a4-48ea-b774-3c6cf79a2c40)
![webcamToImage_1-0](https://github.com/keijiro/UnityMLStableDiffusion/assets/12746646/3ed2deb3-ce81-415b-8de6-2ce84023db27)
![webcamToImage_0-9](https://github.com/keijiro/UnityMLStableDiffusion/assets/12746646/ac7b1802-f330-4ed9-bfd3-75f84c6e1e8d)
thanks,

**Comment by keijiro** [comment]
Okay. It seems working. So, only the prompt property is broken. I'm still not sure why, though.

There are a few things you can try:

- Trying other Stable Diffusion versions (1.5 and 2.1).
- Trying [Hugging Face Diffusers app](https://apps.apple.com/us/app/diffusers/id1666309574?mt=12). It uses the same Core ML library. If it works on your machine, this project should work too.
- Rebuilding the plugin on your side. You can build it by simply executing `build.sh` in the `Plugin` directory.

**Comment by felixopixido** [comment]
So:
    Trying other Stable Diffusion versions (1.5 and 2.1). => no change on 1.5
    Trying Hugging Face Diffusers app. It uses the same Core ML library. If it works on your machine, this project should work too.=> app work fine! so the problem is unity?
    Rebuilding the plugin on your side. You can build it by simply executing build.sh in the Plugin directory. => I try without change
thanks,
